# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Config for Relational DB Servers (3)
  (1..3).each do |i|
    config.vm.define "rdbs#{i}" do |node|
      node.vm.hostname = "rdbs#{i}"
      node.vm.box = "ubuntu/bionic64"
      node.vm.network "private_network", ip: "192.168.16.6#{i+3}"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "rdbs#{i}"
        vb.gui = false
        vb.memory = "512"
        vb.cpus = "1"
      end
      
      node.vm.provision "shell", path: "bootstrapRDBS#{i}.sh"
    end
  end

  # Config for Load balancer
  config.vm.define "lb1" do |node|
    node.vm.hostname = "lb1"
    node.vm.box = "ubuntu/bionic64"
    node.vm.network "private_network", ip: "192.168.16.67"
    
    node.vm.provider "virtualbox" do |vb|
      vb.name = "lb1"
      vb.gui = false
      vb.memory = "512"
      vb.cpus = "1"
    end

    node.vm.provision "shell", path: "bootstrapLoadBalancer.sh", privileged: false
  end

  # Config for web server
  config.vm.define "web1" do |node|
    node.vm.hostname = "web1"
    node.vm.box = "ubuntu/bionic64"
    node.vm.network "private_network", ip: "192.168.16.68"
    
    node.vm.provider "virtualbox" do |vb|
      vb.name = "web1"
      vb.gui = false
      vb.memory = "512"
      vb.cpus = "1"
    end

    node.vm.provision "shell", path: "bootstrapWebServer.sh"
  end

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
end
